// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIebHuRvoa5CNY2ZvvZzGcwPaGpT_lQqc',
    appId: '1:639674866091:web:e6049a984ab8a5d899daee',
    messagingSenderId: '639674866091',
    projectId: 'spotify-3f884',
    authDomain: 'spotify-3f884.firebaseapp.com',
    storageBucket: 'spotify-3f884.appspot.com',
    measurementId: 'G-J0ZZG4ZZ8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqb9oqfIwxRTCVT3U4KXmUJRAOozCD4F8',
    appId: '1:639674866091:android:950a7e2f38624d9999daee',
    messagingSenderId: '639674866091',
    projectId: 'spotify-3f884',
    storageBucket: 'spotify-3f884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhlffpOWCmmYlNBydoSJHTaHu64U1QOdc',
    appId: '1:639674866091:ios:02dc7dc2c08e34d299daee',
    messagingSenderId: '639674866091',
    projectId: 'spotify-3f884',
    storageBucket: 'spotify-3f884.appspot.com',
    iosBundleId: 'com.example.spotify',
  );
}
